# This is an example neoforge.mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://www.github.com/TheDeathlyCow/scorchful/issues"

[[mods]]

modId="${mod_id}"

version="${mod_version}"

displayName="${mod_name}"

displayURL="https://www.thedeathlycow.com/scorchful"


logoFile="assets/icon.png"

# A text field displayed in the mod UI
#credits="" #optional

# The authors of the mod, displayed in the mod UI (optional)
authors="TheDeathlyCow"

# The description text for the mod (multi line!) (#mandatory)
description='''
A mod focused on Heat based survival and combat. Also try Frostiful!
'''

[modproperties.${mod_id}."yumi:entrypoints"]
"yumi:init" = "com.github.thedeathlycow.scorchful.Scorchful"
"yumi:client_init" = "com.github.thedeathlycow.scorchful.client.ScorchfulClient"


# The [[mixins]] block allows you to declare your mixin config to FML so that it gets loaded.
[[mixins]]
config="${mod_id}.mixins.json"

[[mixins]]
config="${mod_id}.client.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="cloth_config"
    type="required"
    versionRange="[${cloth_config_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="fabric_api"
    type="required"
    versionRange="[${ffapi_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="thermoo"
    type="required"
    versionRange="[${thermoo_version},)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="velvet"
    type="required"
    versionRange = "[${velvet_version},)"
    ordering = "AFTER"
    side = "CLIENT"